export const basemapLayers = {
  //county boundaries
  //municipal boundaries
  //transit stations?
};

export const togglableLayers = {
  ipd: {
    key: "ipd",
    id: "Indicators of Potential Disadvantage (2018)",
    type: "geojson",
    data: "https://arcgis.dvrpc.org/portal/rest/services/Demographics/IPD_2018/FeatureServer/0/query?where=geoid10+like+%2742%25%27&outFields=IPD_SCORE&outSR=4326&f=geojson",
    layer: {
      type: "fill",
      paint: {
        "fill-color": [
          "interpolate",
          ["linear"],
          ["get", "ipd_score"],
          9,
          "#ffffd9",
          13,
          "#edf8b1",
          15,
          "#c7e9b4",
          17,
          "#7fcdbb",
          19,
          "#41b6c4",
          21,
          "#1d91c0",
          24,
          "#225ea8",
          27,
          "#253494",
          30,
          "#081d58",
        ],
        "fill-opacity": [
          "interpolate",
          ["linear"],
          ["zoom"],
          0,
          1,
          7,
          0.75,
          9,
          0.5,
          11,
          0.25,
        ],
      },
    },
  },
  cmp: {
    key: "cmp",
    id: "Congestion Management Subcorridor Areas",
    type: "geojson",
    data: "https://arcgis.dvrpc.org/portal/rest/services/Transportation/CMP2019_CorridorSubCorridorAreas/FeatureServer/0/query?where=state='PA'&outFields=WEB_COLOR&returnGeometry=true&geometryPrecision=4&outSR=4326&f=geojson",
    layer: {
      type: "fill",
      paint: {
        "fill-color": ["get", "web_color"],
        "fill-opacity": 0.8,
      },
    },
  },
  connections: {
    key: "connections",
    id: "Connections 2045 Centers",
    type: "geojson",
    data: "https://arcgis.dvrpc.org/portal/rest/services/Planning/LRP_2045_PlanningCenters/FeatureServer/0/query?where=1=1&outFields=lup_type&geometryPrecision=4&outSR=4326&f=geojson",
    layer: {
      type: "fill",
      paint: {
        "fill-color": [
          "case",
          ["==", ["get", "lup_type"], "Metropolitan Center"],
          "#f26522",
          ["==", ["get", "lup_type"], "Metropolitan Subcenter"],
          "#223860",
          ["==", ["get", "lup_type"], "Suburban Center"],
          "#0b6d32",
          ["==", ["get", "lup_type"], "Town Center"],
          "#729faa",
          ["==", ["get", "lup_type"], "Rural Center"],
          "#ed1c24",
          ["==", ["get", "lup_type"], "Planned Town Center"],
          "#9d1d20",
          "#cccccc",
        ],
        "fill-opacity": [
          "interpolate",
          ["linear"],
          ["zoom"],
          0,
          1,
          7,
          0.75,
          9,
          0.5,
          11,
          0.25,
        ],
      },
    },
  },
  freight: {
    key: "freight",
    id: "Freight Centers",
    type: "geojson",
    data: "https://arcgis.dvrpc.org/portal/rest/services/Planning/LRP_2045_Freight_Centers/FeatureServer/0/query?where=1%3D1&outFields=types&outSR=4326&f=geojson",
    layer: {
      type: "fill",
      legend: [
        ["#f4bd48", "International Gateway"],
        ["#ef7e51", "Heavy Industrial"],
        ["#ca4b66", "Distribution and Logistics"],
        ["#883272", "High Tech Manufacturing"],
        ["#312867", "Local Manufacturing and Distribution"],
      ],
      paint: {
        "fill-color": [
          "case",
          ["==", ["get", "types"], "International Gateway"],
          "#f4bd48",
          ["==", ["get", "types"], "Heavy Industrial"],
          "#ef7e51",
          ["==", ["get", "types"], "Distribution and Logistics"],
          "#ca4b66",
          ["==", ["get", "types"], "High Tech Manufacturing"],
          "#883272",
          ["==", ["get", "types"], "Local Manufacturing and Distribution"],
          "#312867",
          "#cccccc",
        ],
        "fill-opacity": [
          "interpolate",
          ["linear"],
          ["zoom"],
          0,
          1,
          7,
          0.75,
          9,
          0.5,
          11,
          0.25,
        ],
      },
    },
  },
  landuse: {
    key: "landuse",
    id: "DVRPC Land Use (2019)",
    url: "https://tiles.dvrpc.org/data/dvrpc-landuse-2015.json",
    type: "vector",
    layer: {
      type: "fill",
      "source-layer": "lu2015",
      popup: {},
      legend: [
        ["rgb(255, 255, 0)", "Residential"],
        ["rgb(194,158,215)", "Industrial"],
        ["rgb(104,104,104)", "Transportation"],
        ["rgb(255,190,190)", "Utility"],
        ["rgb(255,0,0)", "Commerical"],
        ["rgb(190,232,255)", "Institutional"],
        ["rgb(0,132,168)", "Military"],
        ["rgb(230,230,0)", "Recreation"],
        ["rgb(215,215,158)", "Agriculture"],
        ["rgb(168,0,0)", "Mining"],
        ["rgb(76,230,0)", "Wooded"],
        ["rgb(0,197,255)", "Water"],
        ["rgb(165,245,122)", "Undeveloped"],
      ],
      paint: {
        "fill-color": [
          "step",
          ["to-number", ["get", "lu15sub"]],
          "rgb(255, 255, 0)",
          3000,
          "rgb(194,158,215)",
          4000,
          "rgb(104,104,104)",
          5000,
          "rgb(255,190,190)",
          6000,
          "rgb(255,0,0)",
          7000,
          "rgb(190,232,255)",
          8000,
          "rgb(0,132,168)",
          9000,
          "rgb(230,230,0)",
          10000,
          "rgb(215,215,158)",
          11000,
          "rgb(168,0,0)",
          12000,
          "rgb(76,230,0)",
          13000,
          "rgb(0,197,255)",
          14000,
          "rgb(165,245,122)",
        ],
        "fill-opacity": [
          "interpolate",
          ["linear"],
          ["zoom"],
          0,
          1,
          7,
          0.75,
          9,
          0.5,
          11,
          0.25,
        ],
      },
    },
  },
};
